
// This file is automatically generated by Firebase App Hosting.
// Do not edit.

export const firebaseConfig = {
  "projectId": "studio-4614023416-d45cd",
  "appId": "1:758125587848:web:c51a2dc58d0f3e5e3c9e3d",
  "storageBucket": "studio-4614023416-d45cd.appspot.com",
  "apiKey": "AIzaSyC9v97yADQ0s_9WjeLU9EFe3jbGk-5HLwk",
  "authDomain": "studio-4614023416-d45cd.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "758125587848"
};
